title: Anomaly Detection Framework
description: Soemthing something... profit.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: David Wrench
repo_url: "https://github.com/ratchetwrench/aodf"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
